### PR TITLE
v1.2

### PR DESCRIPTION
**Pull request by soyware**
CHANGELOG:
added enable setting
added "yaw only" and "perfect silent angles" to the playback settings
added "nearby" to the draw filter
added max distance setting
added overwrite dialog
made start position appear smoothly
made map's recordings load automatically (from a folder named map's name)
ignore idle ticks at the start and at the end (record / playback)
temporary disable settings that may interfere during recording / playback: airstrafe, desync etc
changed start indicator, now it's an arrow pointing to the end location
removed "draw path" (i can't imagine anyone using it, plus it's ineffective)
removed origin from non start / end record ticks
removed roll and upmove as they are not used
removed saved recordings list
replace unload, load buttons with reload (reloads map's recordings)
changed settings window to a tab
changed delete dialog position
changed recording serialization (old recordings incompatible)
removed indicator color setting
updated recordings, deleted duplicates, re-recorded some jumps, added new ones
other improvements

HOW TO PORT OLD RECORDING TO A NEW FORMAT:
1. rename a file to have an extension ".mr.dat"
2. replace "\[\d+\]=\{\d+\},\r?\n" regex with ""
3. replace "\{\r?\n\}," regex with ""

### CODE REVIEW

**Comment by stqcky** [comment]
Thank you. I will check it out and if everything works I'll merge it

**Comment by stqcky** [comment]
Here are the problems I've found:
- Velocity check in StartRecording does not account for micro movements
- Draw Indicator should be on by default (can be confusing)
- Yaw Only should be off by default (can be confusing)
- Replace loadstring with load(chunk, "", "bt" {}) to account for arbitrary code execution
- Typo in "B Plat.mr.dat" de_mirage recording

**Comment by soyware** [comment]
Not sure what you mean by micro movements, so I just changed comparison to 0, even though you can't move for sub 1 velocity

**Comment by stqcky** [comment]
> Not sure what you mean by micro movements, so I just changed comparison to 0, even though you can't move for sub 1 velocity

I mean the Micromovment type in Ragebot > Anti-Aim > Advanced > Anti-Align Type. It makes you move for about 1.1 velocity thus triggering the velocity check and causing the recording to not start.

**Comment by soyware** [comment]
We disable desync though, must be some other lua constantly changing the setting and I don't think I can fix that

**Comment by stqcky** [comment]
You should just put the velocity threshold to 1.1 so you can start a recording while using micro movements

**Comment by stqcky** [comment]
Alright, looks good!

**Pull request merged**
